spring:
  application:
    name: idp-core-backend
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USER}
    password: ${MAIL_PASS}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  profiles:
    active: dev
  web:
    cors:
      mappings:
        "[/**]":
          allowed-origins: "${CORS_ALLOWED_ORIGINS}"
          allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
          allowed-headers: "*"
          allow-credentials: true
server:
  port: 9091
jwt:
  expiration: 9000000
  issuer: idp-core-backend
  secret: ${JWT_SECRET}
app:
  frontend:
    url: ${FRONTEND_URL}
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS}
  legal:
    consent:
      type: "DATA_PRIVACY"
      version: "v1.0"
      document-path: "https://core.com/static/legal/privacy-policy-v1.pdf"
      document-hash: ${DOCUMENT_LEGAL}